### ISSUE TITLE
Make it work on Elixir 1.14

### ISSUE THREAD

**Issue by wingyplus** [tony612/elixir-grpc-prometheus#2]
This come from issue https://github.com/elixir-grpc/grpc/issues/293. Here is the build log about compilation error: https://github.com/elixir-grpc/grpc/actions/runs/3893947329/jobs/6647249288

**Comment by polvalente** [comment]
https://hexdocs.pm/telemetry_metrics_prometheus/TelemetryMetricsPrometheus.html

We should probably move to a more current strategy of using a Telemetry exporter for prometheus.

Or even, just provide the metrics to be used by any telemetry exporter and direct people on how to use them with prometheus instead.

This could end up deprecating this package fully in favor of having :telemetry in the main repo.

@tony612 thoughts here?

**Comment by wingyplus** [comment]
I see this library has summary metric but the prometheus telemetry doesn't supporting it. :( 

I'm not sure if we use the summary metrics in the interop test.

Ref: https://github.com/elixir-grpc/grpc-prometheus/blob/master/lib/grpc_prometheus/client_interceptor.ex#L60

**Comment by polvalente** [comment]
We can just drop the summary metric. Is there really anything useful there that can't be obtained from other metrics?

**Comment by wingyplus** [comment]
I think no anything concern. :)

**Comment by tony612** [comment]
@polvalente Sounds good given https://github.com/deadtrickster/prometheus.ex looks like outdated from your comments.

For summary, I think histogram is more important than summary :)

**Comment by polvalente** [comment]
@tony612 given elixir-grpc/grpc#229 and elixir-grpc/grpc#299, I think we can actually archive this repository when they are done.

We'd add a note pointing to the Livebook proposed in elixir-grpc/grpc#299 to the README instead. WDYT?

I'm closing this because supporting Elixir 1.14 is a non-issue anyway.

**Comment by tony612** [comment]
@polvalente Sounds good.
